image: elsa/ubu18-clang6:latest

stages:
  - compile
  - test
  - examples

compile:linux-gcc:
  stage: compile
  script:
    - mkdir -p build-linux-gcc
    - cd build-linux-gcc
    - cmake ..
    - make
  artifacts:
    paths:
      - build-linux-gcc/test/
      - build-linux-gcc/examples/
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build-linux-gcc/

compile:linux-clang:
  stage: compile
  script:
    - mkdir -p build-linux-clang
    - cd build-linux-clang
    - cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++
    - make
  artifacts:
    paths:
      - build-linux-clang/test/
      - build-linux-clang/examples/
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build-linux-clang/

tests:
  stage: test
  script:
    - ./build-linux-clang/test/firstTest
    - ./build-linux-gcc/test/firstTest
  tags:
    - linux
examples:
  stage: examples
  script:
    - ./build-linux-clang/examples/xor
    - ./build-linux-gcc/examples/xor
  tags:
    - linux
      