image: elsa/ubu18-clang6:latest

stages:
  - compile
  - test

compile:linux-gcc:
  stage: compile
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/test/
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/

compile:linux-clang:
  stage: compile
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++
    - make
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/

tests:
  stage: test
  script:
    - ./build/test/firstTest
  tags:
    - linux
      